import Charts
import SwiftUI

struct MarketDetailView: View {
    @Environment(OddsightMarketStore.self) private var marketStore
    @State private var isCreatingAlert = false
    let market: Market
    let matchedMarket: MatchedMarket?

    private var quote: BinaryMarketQuote {
        market.quote
    }

    var body: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 12) {
                    HStack {
                        PlatformBadge(platform: market.platform)
                        Text(market.category.rawValue)
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(.secondary)
                        Spacer()
                    }

                    Text(market.title)
                        .font(.title2.weight(.bold))

                    Text(market.normalizedQuestion)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
                .padding(.vertical, 4)
            }

            Section("Market Data") {
                LabeledContent("Implied probability", value: market.probability.percentText)
                LabeledContent("YES bid", value: quote.yesBid?.percentText ?? "Unavailable")
                LabeledContent("YES ask", value: quote.yesAsk?.percentText ?? "Unavailable")
                LabeledContent("NO bid", value: quote.noBid?.percentText ?? "Unavailable")
                LabeledContent("NO ask", value: quote.noAsk?.percentText ?? "Unavailable")
                LabeledContent("Price quality", value: quote.sourceQuality.displayName)
                LabeledContent("24h volume", value: market.volume24h.compactDollarText)
                LabeledContent("Liquidity", value: market.liquidity.compactDollarText)
                LabeledContent("24h move", value: market.probabilityChange24h.signedPointsText)
                LabeledContent("Expiration", value: market.expirationDescription)
            }

            Section("Probability History") {
                ProbabilityHistoryChart(
                    snapshots: marketStore.snapshotHistory[market.id] ?? [],
                    errorMessage: marketStore.historyErrors[market.id]
                )
            }

            if let matchedMarket {
                Section("Matched Market") {
                    let otherMarket = matchedMarket.primaryMarket.id == market.id ? matchedMarket.comparisonMarket : matchedMarket.primaryMarket
                    let discrepancy = matchedMarket.discrepancy

                    VStack(alignment: .leading, spacing: 10) {
                        HStack {
                            Text(matchedMarket.status)
                                .font(.subheadline.weight(.semibold))
                            Spacer()
                            Text("Confidence \(matchedMarket.confidence.percentText)")
                                .font(.subheadline)
                                .foregroundStyle(.secondary)
                        }

                        Divider()

                        MarketComparisonLine(title: market.platform.rawValue, probability: market.probability)
                        MarketComparisonLine(title: otherMarket.platform.rawValue, probability: otherMarket.probability)
                        MarketComparisonLine(title: "Difference", probability: matchedMarket.probabilityDifference)
                        LabeledContent("Comparison quality", value: discrepancy?.sourceQuality.displayName ?? "Unavailable")
                        LabeledContent("Generated by", value: matchedMarket.assessment.generatedBy)
                    }
                    .padding(.vertical, 4)
                }

                Section("Match Assessment") {
                    MatchAssessmentView(assessment: matchedMarket.assessment)
                }

                if let arbitrage = matchedMarket.potentialArbitrage {
                    Section("Potential Arbitrage") {
                        LabeledContent("YES ask", value: arbitrage.yesAsk.percentText)
                        LabeledContent("NO ask", value: arbitrage.noAsk.percentText)
                        LabeledContent("Combined cost", value: arbitrage.combinedCost.currencyText)
                        LabeledContent("Gross profit", value: arbitrage.grossProfit.currencyText)
                        LabeledContent("Gross return", value: arbitrage.grossReturn.percentText)
                        Text("Theoretical only. Fees, slippage, available size, and settlement equivalence are not verified in sample data.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }

            Section("Resolution") {
                Text(market.resolutionSummary)
                    .foregroundStyle(.secondary)
            }

            Section("Source") {
                if let url = URL(string: market.sourceURL) {
                    Link(destination: url) {
                        Label("Open on \(market.platform.rawValue)", systemImage: "arrow.up.forward.app")
                    }
                } else {
                    Text("Source URL unavailable")
                        .foregroundStyle(.secondary)
                }
            }

            Section {
                Button {
                    isCreatingAlert = true
                } label: {
                    Label("Create Probability Alert", systemImage: "bell.badge")
                }
            }
        }
        .navigationTitle("Market")
        .navigationBarTitleDisplayMode(.inline)
        .task(id: market.id) {
            await marketStore.loadHistory(for: market.id)
        }
        .sheet(isPresented: $isCreatingAlert) {
            CreateMarketAlertView(market: market)
        }
    }
}

private struct CreateMarketAlertView: View {
    @Environment(OddsightMarketStore.self) private var marketStore
    @Environment(\.dismiss) private var dismiss
    let market: Market
    @State private var direction: ProbabilityAlertDirection = .risesAbove
    @State private var threshold: Double

    init(market: Market) {
        self.market = market
        _threshold = State(initialValue: min(1, max(0, market.probability + 0.05)))
    }

    var body: some View {
        NavigationStack {
            Form {
                Section("Condition") {
                    Picker("Direction", selection: $direction) {
                        ForEach(ProbabilityAlertDirection.allCases) { direction in
                            Text(direction.displayName).tag(direction)
                        }
                    }
                    LabeledContent("Threshold", value: threshold.percentText)
                    Slider(value: $threshold, in: 0...1, step: 0.01)
                }

                if !marketStore.canCreateAlert {
                    Section {
                        ContentUnavailableView(
                            "Alert limit reached",
                            systemImage: "lock.fill",
                            description: Text("The \(marketStore.currentTier.displayName) plan allows \(marketStore.alertUsageDescription.lowercased()). Plan upgrades are coming later.")
                        )
                    }
                }

                Section("Current Market") {
                    LabeledContent("Probability", value: market.probability.percentText)
                    Text(market.title)
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
            }
            .navigationTitle("New Alert")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        Task {
                            if await marketStore.addAlert(for: market, direction: direction, threshold: threshold) {
                                dismiss()
                            }
                        }
                    }
                    .disabled(!marketStore.canCreateAlert)
                }
            }
        }
        .presentationDetents([.medium])
    }
}

private struct ProbabilityHistoryChart: View {
    let snapshots: [MarketSnapshot]
    let errorMessage: String?

    var body: some View {
        if let errorMessage {
            ContentUnavailableView(
                "History unavailable",
                systemImage: "chart.xyaxis.line",
                description: Text(errorMessage)
            )
        } else if snapshots.count < 2 {
            ContentUnavailableView(
                "Collecting history",
                systemImage: "chart.xyaxis.line",
                description: Text("Oddsight needs at least two observations before it can draw a trend.")
            )
        } else {
            Chart(snapshots, id: \.observedAt) { snapshot in
                AreaMark(
                    x: .value("Observed", snapshot.observedAt),
                    y: .value("Probability", snapshot.probability)
                )
                .foregroundStyle(.cyan.opacity(0.12))

                LineMark(
                    x: .value("Observed", snapshot.observedAt),
                    y: .value("Probability", snapshot.probability)
                )
                .foregroundStyle(.cyan)
                .interpolationMethod(.monotone)
            }
            .chartYScale(domain: 0...1)
            .chartYAxis {
                AxisMarks(position: .leading, values: [0, 0.25, 0.5, 0.75, 1]) { value in
                    AxisGridLine()
                    AxisValueLabel {
                        if let probability = value.as(Double.self) {
                            Text(probability, format: .percent.precision(.fractionLength(0)))
                        }
                    }
                }
            }
            .frame(height: 190)
            .accessibilityLabel("Probability history")
        }
    }
}

private struct MarketComparisonLine: View {
    let title: String
    let probability: Double

    var body: some View {
        HStack {
            Text(title)
            Spacer()
            Text(probability.percentText)
                .font(.body.weight(.semibold))
        }
    }
}

private struct MatchAssessmentView: View {
    let assessment: MatchAssessment

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                MetricPill(title: "Event", value: assessment.eventSimilarity.percentText, tint: .cyan)
                MetricPill(title: "Expiry", value: assessment.expirationSimilarity.percentText, tint: .cyan)
            }

            LabeledContent("Category compatible", value: assessment.categoryCompatible ? "Yes" : "No")

            if !assessment.sharedTerms.isEmpty {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Shared Terms")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Text(assessment.sharedTerms.prefix(10).joined(separator: ", "))
                        .font(.subheadline)
                }
            }

            AssessmentList(title: "Reasons", items: assessment.reasons)
            AssessmentList(title: "Risks", items: assessment.risks)
        }
        .padding(.vertical, 4)
    }
}

private struct AssessmentList: View {
    let title: String
    let items: [String]

    var body: some View {
        if !items.isEmpty {
            VStack(alignment: .leading, spacing: 6) {
                Text(title)
                    .font(.caption)
                    .foregroundStyle(.secondary)

                ForEach(items, id: \.self) { item in
                    HStack(alignment: .top, spacing: 8) {
                        Image(systemName: title == "Risks" ? "exclamationmark.circle" : "checkmark.circle")
                            .font(.caption)
                            .foregroundStyle(title == "Risks" ? .orange : .green)
                            .padding(.top, 2)
                        Text(item)
                            .font(.subheadline)
                            .foregroundStyle(.secondary)
                    }
                }
            }
        }
    }
}

private extension PriceSourceQuality {
    var displayName: String {
        switch self {
        case .executableBidAsk:
            return "Executable bid/ask"
        case .midpoint:
            return "Midpoint"
        case .lastTrade:
            return "Last trade"
        case .unavailable:
            return "Unavailable"
        }
    }
}

private extension Double {
    var currencyText: String {
        formatted(.currency(code: "USD").precision(.fractionLength(2)))
    }
}

#Preview {
    NavigationStack {
        MarketDetailView(market: SampleOddsightData.kalshiFed, matchedMarket: SampleOddsightData.fedMatch)
    }
    .environment(OddsightMarketStore())
}
